export const data = [
  {
    id: 1,
    img: "https://images.immediate.co.uk/production/volatile/sites/30/2021/04/Raspberry-Mojito-a9cb8d4.jpg",
    name: "ACFE",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "ASACE",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/616836/pexels-photo-616836.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "E",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/2480828/pexels-photo-2480828.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "C",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/1304541/pexels-photo-1304541.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "CE",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/2336667/pexels-photo-2336667.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "AC",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/1280364/pexels-photo-1280364.jpeg?auto=compress&cs=tinysrgb&w=300",
    name: "ACEAAS",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/4686940/pexels-photo-4686940.jpeg?auto=compress&cs=tinysrgb&w=300",
    name: "ACEAA",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/1194028/pexels-photo-1194028.jpeg?auto=compress&cs=tinysrgb&w=300",
    name: "ACD",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/1564534/pexels-photo-1564534.jpeg?auto=compress&cs=tinysrgb&w=300",
    name: "ASA",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/4667081/pexels-photo-4667081.jpeg?auto=compress&cs=tinysrgb&w=300",
    name: "ACDE",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 13,
    img: "https://images.pexels.com/photos/1058434/pexels-photo-1058434.jpeg?auto=compress&cs=tinysrgb&w=300",
    name: "RACE",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 14,
    img: "https://images.pexels.com/photos/4457151/pexels-photo-4457151.jpeg?auto=compress&cs=tinysrgb&w=300",
    name: "BCE",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
  {
    id: 15,
    img: "https://images.pexels.com/photos/2109099/pexels-photo-2109099.jpeg?auto=compress&cs=tinysrgb&w=300",
    name: "A",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, doloremque.",
  },
];
